#SingleInstance, Force
#NoTrayIcon

:*:__author::__author__
:*:__enter::__enter__
:*:__exit::__exit__
:*:__init::__init__
:*:__main::__main__
:*:__name::__name__
:*:airpot::airport
:*:badu::baidu
:*:benkui::bengkui
:*:buidl::build
:*:cahung::chuang
:*:chaung::chuang
:*:Excude::Excuse
:*:flsah::flash
:*:fnag::fang
:*:gengju::genju
:*:hcuangjian::chuangjian
:*:iamge::image
:*:jain::jian
:*:jaing::jiang
:*:jiefneg::jiefeng
:*:Lable::Label
:*:laing::liang
:*:laio::liao
:*:Leagal::Legal
:*:localohost::localhost
:*:mny::my
:*:musix::music
:*:naing::niang
:*:ngxin::nginx
:*:pritn::print
:*:qaing::qiang
:*:renturn::return
:*:retrun::return
:*:retun::return
:*:shaung::shuang
:*:shiab::shiba
:*:Sned::Send
:*:bnag::bang
:*:cnag::cang
:*:dnag::dang
:*:fnag::fang
:*:gnag::gang
:*:hnag::hang
:*:hnag::hang
:*:knag::kang
:*:lnag::lang
:*:mnag::mang
:*:nnag::nang
:*:pnag::pang
:*:rnag::rang
:*:snag::sang
:*:tnag::tang
:*:wnag::wang
:*:ynag::yang
:*:xaing::xiang
:*:zhaun::zhuan
:*:zhufnag::zhufang
:*:zhuxaio::zhuxiao
:*:ifocnfig::ifconfig
:*:dokcer::docker
:*:docekr::docker
:*:clone::clone
